### ISSUE TITLE
添加黑名单用户功能

### ISSUE THREAD

**Issue by FLYEMOJ1** [LittleSkinCommspt/commspt-bot#22]
如标题，因 [于 LSCommspt-Manual 发起的 Merge request 16](https://github.com/LittleSkinCommspt/commspt-bot-manual/pull/16) 发起该 Issue 进行功能性添加记录。

**Comment by gxres042** [comment]
这个功能之前有，但是后面被 Xiao_Jin 砍掉了......
有空我看一下 Commit 记录，看能不能找到之前被删掉的源码

**Comment by SerinaNya** [comment]
不会添加此功能
