### ISSUE TITLE
[Feature] 添加 LittleSkin 传统加载皮肤的 sha256 计算

### ISSUE THREAD

**Issue by Nofated095** [LittleSkinCommspt/commspt-bot#40]
如题，由于 LittleSkin 最近几日频繁出现 CDN 刷新不及时的问题，故提出这个。

简单来说就是传统加载因为没人用，CDN 几乎不存在缓存，所以可以利用对比传统加载加载的皮肤和 CSL 或 Ygg 加载的皮肤的 hash 数据从而判断是否出现了 CDN 缓存延迟。

应该是只要套用  get_texture.py 即可，但是要让机器人来计算文件的 SHA-256 数据。

**Comment by gxres042** [comment]
Why don't you assigned Xiao_Jin?

**Comment by SerinaNya** [comment]
🉑，写完开 PR
