### ISSUE TITLE
[off-topic] 这个qqbot能用吗

### ISSUE THREAD

**Issue by hcr707305003** [LittleSkinCommspt/commspt-bot#5]

**Comment by gxres042** [comment]
请问用途是拿来做什么的？

**Comment by hcr707305003** [comment]
用于群聊功能和点歌，没了

**Comment by gxres042** [comment]
目前并不支持
为了更好协助 LittleSkin 的用户，我们使用 Python 3 以及 Mirai 写出了这个 QQ BOT 组件。但是，对于目前来说，并不需要音乐之类的功能，只是协助进行用户帮助之类的。
谢谢。

**Comment by hcr707305003** [comment]
> 谢谢，我就是想找个bot源码然后学习一下

例如 `commandparser.py` 是比较具有参考意义的

**Comment by SerinaNya** [comment]
宁好，我们这个你拿到了也运行不了呢，因为有一些敏感文件我们并没有公开。不过，我们公开的代码足以让您学习。
