### ISSUE TITLE
[Feature Request] 新增指令 &clfcsl.latest

### ISSUE THREAD

**Issue by ZekerZhayard** [LittleSkinCommspt/commspt-bot#6]
「在 1.7.10 中需要同时安装最新 Forge 版的 CustomSkinLoader 和 CompatibilityLayerForCustomSkinLoader （https://www.mcbbs.net/thread-1109996-1-1.html）」

**Comment by Restent** [comment]
是要加语言库吗？（

**Comment by SerinaNya** [comment]
```
在 1.7.10 中需要同时安装最新 Forge 版的 CustomSkinLoader 和 CompatibilityLayerForCustomSkinLoader
你可以在 https://www.mcbbs.net/thread-1109996-1-1.html%EF%BC%89%E3%80%8D 下载到它
```
这样如何？

**Comment by ZekerZhayard** [comment]
> ```
> 在 1.7.10 中需要同时安装最新 Forge 版的 CustomSkinLoader 和 CompatibilityLayerForCustomSkinLoader
> 你可以在 https://www.mcbbs.net/thread-1109996-1-1.html%EF%BC%89%E3%80%8D 下载到它
> ```
> 
> 这样如何？

可
