### ISSUE TITLE
[disscussion] 加入 antiSpamAbuse

### ISSUE THREAD

**Issue by SerinaNya** [LittleSkinCommspt/commspt-bot#8]
传入：`str`  复读的文字，例如 `草`

返回：`bool` 是否可以复读

请在下面附上你的解决方案

**Comment by Glavo** [comment]
```python
import time

time_dict = {}

def antiSpamAbuse(str):
  t = time_dict.get(str)
  now = time.time()
  if t == None or (now - t > 30):
    time_dict[str] = now
    return True
  else:
    return False
```

**Comment by SerinaNya** [comment]
> ```python
> import time
> 
> time_dict = {}
> 
> def antiSpamAbuse(str):
>   t = time_dict.get(str)
>   now = time.time()
>   if t == None or (now - t > 10):
>     time_dict[str] = now
>     return True
>   else:
>     return False
> ```

能写包装成一个 class 吗，还有，这个变量名能正经点吗？

**Comment by gxres042** [comment]
生草复读机不是早弄好了吗，这又是什么新功能

**Comment by SerinaNya** [comment]
> 生草复读机不是早弄好了吗，这又是什么新功能

有滥用情况

**Comment by Glavo** [comment]
我对 Python 也不熟（指要边看入门教程边写代码），你按照自己代码风格包一下改改变量名更好些吧

**Comment by gxres042** [comment]
那我建议你用像指令功能的，能把 BAN 也给使用，就是我们平常写代码那种啊（
@jinzhijie

**Comment by gxres042** [comment]
那种的话暂时能达到生草复读机所需求的，也可以限制被封禁用户不能使用复读机。

**Comment by gxres042** [comment]
如果你觉得麻烦的话，可以试试把草也搞一个封禁，然后外包管理员封禁。

**Comment by SerinaNya** [comment]
@Restent 被封禁者无法触发生草复读机，这是已经实现了的。但是在复读这方面直接 ban 的话，未免也太狠了。如果加阈值的话，倒是可以考虑考虑

**Comment by SerinaNya** [comment]
已找到代替方案
